
spring:
    profiles:
        active:
        - ${PROFILE}
    application:
        name: bookings
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure: ERROR